name: Update Website

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@v3
      - name: Update Website
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
          cd /usr/share/korbs-studio/blue-runners/website/_work/blueanimates/blueanimates/_site/
          sudo cp -R ./* /usr/share/nginx/blueanimates/website/
